version: '3.8'

services:
  db:
    image: 'postgres:13'
    environment:
      POSTGRES_PASSWORD: password0
    networks:
      - backend 
    ports:
      - '5432:5432'
    volumes:
      - 'db:/data'


  redis:
    image: 'redis:3.2-alpine'
    networks:
      - backend 
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'



  api:
    build: "./rails_api_base"
    depends_on:
      - 'db'
    env_file:
      - '.env'
    networks:
      - frontend
      - backend 
    ports:
      - '3000:3000'
    volumes:
      - 'rails:/app'


  web:
    build: "./react-base"
    env_file:
      - '.env-react'
    networks:
      - frontend
      - backend 
    ports:
      - '8080:8080'
    volumes:
      - './react-base:/app'



volumes:
  db: {}
  redis: {}
  rails: {}

networks:
  frontend:
  backend: 

